### PR TITLE
Install Agda standard library outside lib/prim

### PR DESCRIPTION
**Pull request by bafain**
When Agda modules are placed under `lib/prim` it seems _impossible to not load them_. Install the standard library in `lib/stdlib` instead and use the [library management system](https://agda.readthedocs.io/en/v2.5.2/tools/package-system.html) to load or unload it.

### CODE REVIEW

**Comment by bafain** [comment]
Does this resolve [FS#56637](https://bugs.archlinux.org/task/56637) ("[agda-stdlib] Cannot be used as a dependency with the AGDA packaging system") as well?

**Comment by bafain** [comment]
The full installation path would be `/usr/share/agda/lib/stdlib`. Other distros seem to install the Agda standard library in `/usr/share/agda-stdlib`.

**Comment by felixonmars** [comment]
Mostly merged in agda-stdlib 0.16.1. Sorry for the very long delay!

**Comment by bafain** [comment]
Agda libraries need to be registered before they can be used. What do you think about displaying the registration instructions as part of the `post_install` script (see `agda-stdlib.install` on the branch of this PR)?

**Comment by felixonmars** [comment]
Arch prefers to show little to no install instructions for these AFAIK, because this should belong to the wiki :)

**Comment by bafain** [comment]
Oh, OK. Thanks.

**Pull request closed without merging**
